### ISSUE TITLE
搜索的子分类显示问题

### ISSUE THREAD

**Issue by too** [FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io#25]
![image](https://user-images.githubusercontent.com/171673/54993654-57363000-4ffd-11e9-9fa7-118c860fc0d2.png)

这里应该只有一级吧？bug？

**Comment by TechQuery** [comment]
不懂你的点……

**Comment by too** [comment]
我以为 workshop 和 activity 是平级的分类，这样看来是一个子类哇？ 那我理解错了
